Imports System.IO
Imports DevExpress.Drawing
Imports DevExpress.XtraCharts

Namespace CustomLegendItemSample
    Partial Public Class Form1
        Inherits Form

        Public Sub New()
            InitializeComponent()
        End Sub
        Private Sub Form1_Load(ByVal sender As Object, ByVal e As EventArgs) Handles MyBase.Load
            ' Create a new custom item.
            Dim item As New CustomLegendItem()
            chart.Legend.CustomItems.Add(item)
            ' Specify its text and marker.
            item.Text = "Custom Legend Item"
            Dim outfile As New FileStream("Image\DXLogo_16x16.png", FileMode.Open)
            Dim image As DXImage = DXImage.FromStream(outfile)
            item.MarkerImage.DXImage = image
            ' Set a value indicating that both autogenerated and custom items are displayed.
            chart.Legend.ItemVisibilityMode = LegendItemVisibilityMode.AutoGeneratedAndCustom
        End Sub
    End Class
End Namespace
